import type { WorkspaceApplication } from '../types'

export const workspaceApplications: WorkspaceApplication[] = [
  {
    id: 'todo',
    name: 'To-Do',
    description: 'Daily priorities, task ownership and team execution.',
    route: '/todo',
    folderPath: 'todo (2)',
    accent: '#246bfe',
    status: 'Workspace native',
    metric: 'Board, calendar, focus & reporting',
    enabled: true,
    glyph: 'TD',
  },
  {
    id: 'cg-studio',
    name: 'CG Studio',
    description: 'Creative production, poster workflows and client content.',
    externalUrl: import.meta.env.VITE_CG_STUDIO_URL || undefined,
    folderPath: 'cgstudio',
    accent: '#014641',
    status: 'Live',
    metric: '12 projects in production',
    enabled: Boolean(import.meta.env.VITE_CG_STUDIO_URL),
    glyph: 'CG',
  },
  {
    id: 'finora',
    name: 'Finora',
    description: 'Invoices, quotations, expenses and payment tracking.',
    externalUrl: import.meta.env.VITE_FINORA_URL || undefined,
    folderPath: 'Finora',
    accent: '#91d632',
    status: 'Live',
    metric: '₹1,48,500 awaiting payment',
    enabled: Boolean(import.meta.env.VITE_FINORA_URL),
    glyph: 'FN',
  },
  {
    id: 'vault',
    name: 'Vault',
    description: 'Company knowledge, SOPs, contracts, templates and brand assets.',
    route: '/vault',
    accent: '#111111',
    status: 'Workspace native',
    metric: '12 documents updated this week',
    enabled: true,
    glyph: 'VT',
  },
  {
    id: 'truhyre',
    name: 'TruHyre',
    description: 'Jobs, candidates, clients and recruitment delivery.',
    externalUrl: import.meta.env.VITE_TRUHYRE_URL || undefined,
    accent: '#b5121b',
    status: import.meta.env.VITE_TRUHYRE_URL ? 'Connected' : 'Coming soon',
    metric: '8 active positions',
    enabled: Boolean(import.meta.env.VITE_TRUHYRE_URL),
    glyph: 'TH',
  },
  {
    id: 'growth-engine',
    name: 'Growth Engine',
    description: 'Leads, clients, follow-ups and growth operations.',
    externalUrl: import.meta.env.VITE_GROWTH_ENGINE_URL || undefined,
    accent: '#e87929',
    status: import.meta.env.VITE_GROWTH_ENGINE_URL ? 'Connected' : 'Coming soon',
    metric: '14 follow-ups pending',
    enabled: Boolean(import.meta.env.VITE_GROWTH_ENGINE_URL),
    glyph: 'GE',
  },
]
